### ISSUE TITLE
Toasts don't show on ios

### ISSUE THREAD

**Issue by mcordes** [mdanishs/nativescript-toasts#1]
This is working great for me on an android platform, but for ios I just don't see the toasts. I have cocoapods installed and I'm running the app via the ios emulator. Is there something I need do other than install your nativescript plugin?

**Comment by mdanishs** [comment]
It would be good if you can give some more detail, I have tried it, it is working fine. 
Can you tell your iOS and nativescript-version? I'll test with it.

**Comment by mdanishs** [comment]
@mcordes any updates? or can I close the issue?

**Comment by mcordes** [comment]
This was definitely an issue on my end. Sorry for the confusion and thanks for a cool library.
